name: api_doc_reader
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  effective_dart: ^1.2.1

  test: ^1.6.0

dependencies:
  html: ^0.14.0
